# LaTeX

For many authors, the main  of long reports or books, the primary output will be LaTeX. In this chapter, we discuss approaches which can be used to customise the output of PDF reports.

Users should approach with a note of caution. One of the major benefits of R Markdown is the fact that a single source document can create documents with multiple formats. By tailoring your work to a single output format (PDF/Word/HTML), you may improve the appearance and performance of a single output but at the expense of this tranferability.

## Inserting Commands

## LaTeX preamble




## Multi-figure plots

If we need to print multiple output graphs or figures, there are several ways this can be achieved. 

## Cross-output

As explained in https://bookdown.org/yihui/rmarkdown/r-code.html#figures of @xie2018, we can place multiple figures side-by-side using the `fig.hold='hold'` along with the `out.width` option. As an example below, we have set the `out.width="50%"`:

```{r fig-sub-2, fig.show ="hold", out.width = "50%", fig.cap="Side-by-side figures", echo = TRUE}
plot(1:10)
plot(rnorm(10), pch=19)
```

The main benefits of this approach is that it is easily achieved, and also works for both PDF and HTML outputs.
