## Add Custom Headers and Footers
<!--- https://stackoverflow.com/questions/25329375/creating-a-footer-for-every-page-using-r-markdown --->
<!--- https://tex.stackexchange.com/questions/139139/adding-headers-and-footers-using-pandoc --->

We can use LaTeX package **fancyhdr** to customise the header and footer of PDF outputs. It provides several commands that allow you to customize the header and footer lines of your document. For a more complete guide, please refer to the [full documentation](http://tug.ctan.org/tex-archive/macros/latex/contrib/fancyhdr/fancyhdr.pdf). To begin with, we must load the package and change the header style:

```latex
\usepackage{fancyhdr}
\pagestyle{fancy}
```

The package offers three different interfaces, but we will use the commands `\fancyhead` and `\fancyfoot`. The syntax for the formatting `\fancyhead[selectors]{output text}`, whereby the selectors state which part of the header we wish to customize. We can use the following selectors for the page locators:

- **E** for even page
- **O** for odd page
- **L** for left side
- **C** for centered
- **R** for right side

For example, `\fancyhead[LE,RO]{Your Name}` will print the text "Your Name" on the Left side of the header for Even pages, and the Right side for Odd pages. We can combine this with additional LaTeX commands to extract details from our document for each page:

- `\thepage`: adds number of the current page.
- `\thechapter`: adds number of the current chapter.
- `\thesection`: adds number of the current section.
- `\chaptername`: adds the word "Chapter" in English or its equivalent in the current language.
- `\leftmark`: adds name and number of the current top-level structure in uppercase letters.
- `\rightmark`: adds name and number of the current next to top-level structure in uppercase letters.


Piecing this components together, a complete example is presented below.

This could be inserted in the document, or another `header.tex` file :

```latex
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[CO,CE]{Your Document Header}
\fancyfoot[CO,CE]{And this is a fancy footer}
\fancyfoot[LE,RO]{\thepage}
```

If in an external `.tex` file, then it could be included in the header of our `rmarkdown::pdf_document` format:

```yaml
---
title: "Document with header and footer"
output: 
  pdf_document:
    includes:
      in_header: header.tex
---
```

The `includes` feature of `pdf_document` is presented in [Advanced customisation](https://bookdown.org/yihui/rmarkdown/pdf-document.html#includes-1) of @xie2018.

An alternative,^[You cannot use both as `in_header:` in yaml will currently override the content of pandoc variable `header-includes`] it could also be included directly in header to a rmarkdown document within the YAML using the pandoc variable `header-includes`:

```yaml
---
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[CO,CE]{Your Document Header}
- \fancyfoot[CO,CE]{And this is a fancy footer}
- \fancyfoot[LE,RO]{\thepage}
output: pdf_document
---
```

### Force Header and footer for every page
<!--- https://stackoverflow.com/questions/30922602/creating-a-footer-for-every-page-including-first-using-r-markdown --->

By default, headers and footers will not be displayed on the first page of your PDF document. If we wish to show our footer on the front page, we must include an additional line `\fancypagestyle{plain}{\pagestyle{fancy}}`.

As an example in the YAML frontmatter specification

```yaml
---
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[CO,CE]{YOur Document Header}
- \fancyfoot[CO,CE]{And this is a fancy footer}
- \fancyfoot[LE,RO]{\thepage}
- \fancypagestyle{plain}{\pagestyle{fancy}}
output: pdf_document
---
```
