## Bibliographies and citations

<!--- https://stackoverflow.com/questions/32946203/including-bibliography-in-rmarkdown-document-with-use-of-the-knitcitations --->

R Markdown makes it easy include citations within your document by using pandoc. For a comprehensive overview, we recommend [Section 2.8](https://bookdown.org/yihui/bookdown/citations.html) of @xie2016bookdown However, the basic usage requires us to specify a bibliography file using the `bibliography` metadata field in the YAML. For example:


```{yaml, eval = FALSE}
---
output: html_document
bibliography: references.bib  
---
```

where the A BibTeX database is a plain-text file that consists of bibliography entries like this:

```
@Manual{R-base,
  title = {R: A Language and Environment for Statistical
    Computing},
  author = {{R Core Team}},
  organization = {R Foundation for Statistical Computing},
  address = {Vienna, Austria},
  year = {2016},
  url = {https://www.R-project.org/},
}
```

Items can be cited directly within the documentation using the first line `@R-base`.

### Add item to bibliography without using it 

By default, the bibliography will only display items which are directly referenced in the document. If you want to include items in the bibliography without actually citing them in the body text, you can define a dummy `nocite` metadata field and put the citations there. This can be included anywhere in the document but it is normally best to place it at the end of the document:

```
# References
---
nocite: |
 @item1, @item2
...
```


### Add all items to bibliography

If we do not wish to explicitally state all of the items within the bibliography but would still like them to show them in our references, we can use the following syntax:

```md
---
nocite: '@*'
...
```

This will force all items to be displayed in the bibliography.




