## Set Date to Current Date

<!--- https://stackoverflow.com/questions/23449319/yaml-current-date-in-rmarkdown --->

It may be useful for the date of the knitted R Markdown document to automatically update each time we rerun the file. To do this, we can add R code directly to the `date` field in the YAML, and use the `Sys.time()` function to extract the current date. As this function will by default provide the date and time, we must specify the desired date time format as shown below:

```{yaml, eval = FALSE}
---
date: "`r format(Sys.time(), '%d %B, %Y')`"
---
```

This will automatically update each time you Knit your document i.e. `r format(Sys.time(), '%d %B, %Y')`. If we wish to customize the format of the dates, we can alter the time format by providing our own text string. Some examples are shown as follows:

- `%B %Y`: `r format(Sys.time(), '%B %Y')`
- `%d/%m/%y`: "`r format(Sys.time(), '%d/%m/%y')`
- `%d/%m/%y`: `r format(Sys.time(), '%a %d %b')`

A full table of POSIXct formats is shown in Table \@ref(tab:dateTimeFormats), which allows users to construct their required date format.

```{r dateTimeFormats, echo = FALSE}
formats <-
  read.table(sep = "\t", header = TRUE,  check.names = FALSE, text = 
"Code	Meaning	Code	Meaning
%a	Abbreviated weekday	%A	Full weekday
%b	Abbreviated month	%B	Full month
%c	Locale-specific date and time	%d	Decimal date
%H	Decimal hours (24 hour)	%I	Decimal hours (12 hour)
%j	Decimal day of the year	%m	Decimal month
%M	Decimal minute	%p	Locale-specific AM/PM
%S	Decimal second	%U	Decimal week of the year (starting on Sunday)
%w	Decimal Weekday (0=Sunday)	%W	Decimal week of the year (starting on Monday)
%x	Locale-specific Date	%X	Locale-specific Time
%y	2-digit year	%Y	4-digit year
%z	Offset from GMT	%Z	Time zone (character)")

knitr::kable(formats, caption = "Date Time Formats within R")
```

As a final note, you may even want to include some explanatory text along with the date. We can easily add any text such as "Last Compiled on" before the R code as follows:

```{yaml, eval = FALSE}
---
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
---
```

