## Adding Multiple Authors to Document

<!--- https://stackoverflow.com/questions/26043807/multiple-authors-and-subtitles-in-rmarkdown-yaml --->

We can add multiple authors to a R Markdown document within the YAML in a number of ways. If we simply want to list them on the same line, we can provide a text string to the document:

```yaml
---
title: "Untitled"
author: "John Doe, John Smith"
---
```

Alternatively, if we wish for each entry to be on its own line we can provide a list of entries to the YAML field. This can be useful if you wish to include further information about each author such as an email address or instituion:

```yaml
---
author: 
- John Doe, Institution One
- John Smith, Institution Two
---
```

We can make use of the markdown syntax `^[]` to add additional information as a footnote to the document. This may be more useful if you have extended information you wish to include for each author, such as providing a contact email, address etc. The exact behaviour will depend on the output format (HTML/PDF/Word):

```yaml
---
author:
- John Doe^[Institution One, email@domain.com]
- John Doe 2^[Institution Two, email2@domain.com]
---
```

Certain R Markdown templates will allow you to specify additional parameters directly within the YAML. For example, the [Radix](https://rstudio.github.io/radix/) output format allows `url`, `affiliation` and `affiliation_url` to be specified. We must first install the Radix package from GitHub:

```{r, echo = TRUE, eval = FALSE}
devtools::install_github("rstudio/radix")
```
We can use the new format by changing the `output` option as specified below:

```yaml
---
title: "Radix for R Markdown"
author:
  - name: "JJ Allaire"
    url: https://github.com/jjallaire
    affiliation: RStudio
    affiliation_url: https://www.rstudio.com
output: radix::radix_article
---
```

