## Customising knitr options

There are more than 40 different chunk options which can be used to fine-tune the behaviour of **knitr** when processing R chunks. [Section 2.8](https://bookdown.org/yihui/rmarkdown/r-code.html) of @xie2018 provides a subset of these, while the full list of these variables is available [https://yihui.name/knitr/options/](https://yihui.name/knitr/options/).

This section aims to provides some useful recipes on some commonly used configurations within R Markdown documents.

### Hide code and all outputs

We often wish to setup our R Markdown documents by loading a series of packages. Instead of using separate commands to R source code (`echo=FALSE`), hide text output (`results='hide'`), hide warnings (`warnings=FALSE`), hide messages (`messages=FALSE`) and so on, we can suppress all forms of output elements using the `include=FALSE` setting as shown below:

````
`r ''````{r, include=FALSE}

```
````

With `include=FALSE`, the code chunk will be evaluated (unless `eval=FALSE`), but the output will be completely suppressed.

### Remove hashes from code output

<!--- https://stackoverflow.com/questions/15081212/remove-hashes-in-r-output-from-r-markdown-and-knitr --->

By default, R code output will have hashes `#` inserted in front of the outputted code. We can alter this behaviour by using the `comment` chunk option. If we only want to change the output for a single block we can include it directly within the code block. For example:

````
`r ''````{r include=FALSE, comment = NA}
plot(cars)
```
````

It is typically more useful to change this globally, so that all your code chunks have the same appearrance. We can change this globally using the `opts_chunk$set` option:

````
`r ''````{r include=FALSE}
knitr::opts_chunk$set(comment = NA)
```
````


