## kableExtra

The **kableExtra** package [@R-kableExtra] is designed to extend the basic functionality of tables produced using `kable`. As explained by the package author, the intention with using **kableExtra** is that you can:

- Use default base `kable()` for all simple tables
- Use `kable()` with **kableExtra** to generate 90 % of complex/advanced/self-customized/beautiful tables in either HTML or LaTeX
- Only have to mess with raw HTML/LaTeX in the last 10% cases where kableExtra cannot solve the problem

This section aims to provide a quick overview of some of the main principles of **kableExtra**, and provides some examples of how you may wish to integrate it into your document. For extensive documentation, readers are recommended to check the [documentation online](https://haozhu233.github.io/kableExtra/), which provides full details on how the outputs can be customised for both [HTML](https://haozhu233.github.io/kableExtra/awesome_table_in_html.html) and [LaTeX](https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf) outputs.

### Setup

**kableExtra** is available to download through CRAN: 

```{r kableExtra, echo=TRUE, eval=FALSE}

# Install from CRAN
install.packages("kableExtra")

# install the development version
devtools::install_github("haozhu233/kableExtra")
```

### Customising HTML

### Customising PDF