# Formatting

One of the strengths of the markdown language is that it's simplicity makes it very easy to read even to newcomers to understand. This is one of its key design principles, and as outlined creator of the markdown language:

> A Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions. – [John Gruber](http://daringfireball.net/projects/markdown/syntax#philosophy)

However, this comes at a cost of customisation, and many of the features which users of typical word processors are used to are not directly accessible. This includes:

- Changing font size
- Changing font colour
- Editing font alignment
- Indenting text

It can be helpful for such features to be included within documents. This chapter provides an extended guide to the basics of  the R Markdown language, and highlights how we can customise the appearance and styling within an R Markdown document.

```{block2, type = "rmdnote"}
If you need a reminder in the basics of the markdown language, the [R Markdown cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf) provides a good overview of the basic syntax.
```
